package com.iddel.spt;

public interface TableConstants {
	
	String USER_ID = "USER_ID";
	String USER_FIRST_NAME = "USER_FIRST_NAME";
	String USER_LAST_NAME = "USER_LAST_NAME";
	String USER_EMAIL = "USER_EMAIL";
	String USER_PASSWORD = "USER_PASSWORD";
	String USER_STATUS = "USER_STATUS";
	String USER_PHONE = "USER_PHONE";
	String USER_ADDRESS = "USER_ADDRESS";
	String USER_COUNTRY = "USER_COUNTRY";
	String IS_ADMIN = "IS_ADMIN";
	String USERS = "USERS";
	
	String PROJECT_ID ="PROJECT_ID";
	String PROJECT_NAME ="PROJECT_NAME";
	String PROJECT_DESC ="PROJECT_DESC";
	String CREATED_BY ="CREATED_BY";
	String CREATED_DATE ="CREATED_DATE";
	String UPDATED_BY ="UPDATED_BY";
	String UPDATED_DATE = "UPDATED_DATE";
	String USER_PROJECTS = "USER_PROJECTS";
	
	String FORM_TYPES = "FORM_TYPES";
	String FORM_TYPE_ID = "FORM_TYPE_ID";
	String FORM_NAME = "FORM_NAME";
	String FORM_DESC = "FORM_DESC";
	
}
